// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7yZCKcpUJxq_1ibt847BWtNqb2uN0xcM',
    appId: '1:159469446003:web:079f07ba268cef87d29b06',
    messagingSenderId: '159469446003',
    projectId: 'flutter-app-ffb9f',
    authDomain: 'flutter-app-ffb9f.firebaseapp.com',
    storageBucket: 'flutter-app-ffb9f.firebasestorage.app',
    measurementId: 'G-SPM2BM1T3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbObYAn3T5nhvjMofpEXN7S5SoK0ec9g',
    appId: '1:159469446003:android:0c75610d87659bc2d29b06',
    messagingSenderId: '159469446003',
    projectId: 'flutter-app-ffb9f',
    storageBucket: 'flutter-app-ffb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtlU0JtlOn3JIr5krUW244vlWtQMMFQg',
    appId: '1:159469446003:ios:afa319565144b334d29b06',
    messagingSenderId: '159469446003',
    projectId: 'flutter-app-ffb9f',
    storageBucket: 'flutter-app-ffb9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtlU0JtlOn3JIr5krUW244vlWtQMMFQg',
    appId: '1:159469446003:ios:afa319565144b334d29b06',
    messagingSenderId: '159469446003',
    projectId: 'flutter-app-ffb9f',
    storageBucket: 'flutter-app-ffb9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7yZCKcpUJxq_1ibt847BWtNqb2uN0xcM',
    appId: '1:159469446003:web:367ee5cc3336a590d29b06',
    messagingSenderId: '159469446003',
    projectId: 'flutter-app-ffb9f',
    authDomain: 'flutter-app-ffb9f.firebaseapp.com',
    storageBucket: 'flutter-app-ffb9f.firebasestorage.app',
    measurementId: 'G-NL75D8E397',
  );
}
